### ISSUE TITLE
running app outside application folder crashes app

### ISSUE THREAD

**Issue by jmecosta** [David-Desmaisons/Neutronium#5]
hi

search path for dlls is searching starting in the currect working directory, supose it needs to use application folder instead.

the chromium dlls fail to be found currently

thanks and regards

**Comment by David-Desmaisons** [comment]
@jmecosta , I am not sure I fully understand your scenario. If you want to deploy a Neutronium application, you need to copy every file from the bin directory, including the cef folder and its subfolder that contains cef binary files

**Comment by jmecosta** [comment]
so, i get this exception when running outside the folder that contains my .exe

Application: BuildOnlyApp.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: Chromium.CfxException
   at Chromium.CfxApi.FindLibraries(System.String ByRef, System.String ByRef)
   at Chromium.CfxApi.Load()
   at Chromium.CfxApi.Probe()
   at Chromium.CfxRuntime.ExecuteProcess(Chromium.CfxApp)
   at Chromium.CfxRuntime.ExecuteProcess()
   at Chromium.WebBrowser.BrowserProcess.Initialize()
   at Chromium.WebBrowser.ChromiumWebBrowser.Initialize()
   at Neutronium.WebBrowserEngine.ChromiumFx.Session.ChromiumFxSession..ctor(System.Action`1<Chromium.CfxSettings>)
   at Neutronium.WebBrowserEngine.ChromiumFx.Session.ChromiumFxSession.GetSession(System.Action`1<Chromium.CfxSettings>)
   at Neutronium.WebBrowserEngine.ChromiumFx.ChromiumFXWPFWebWindowFactory..ctor(System.Action`1<Chromium.CfxSettings>)
   at Neutronium.WebBrowserEngine.ChromiumFx.ChromiumFxWebBrowserApp.GetWindowFactory()
   at Neutronium.WPF.HTMLApp.OnStartup(System.Windows.StartupEventArgs)
   at System.Windows.Application.<.ctor>b__1_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at BuildOnlyApp.App.Main()


We have a wrapper that calls the Neutronium application, it does not set the working path the the place where the Neutronium application is. So it crashed, i ve fixed from my side by setting the working dir to there.

But i think this use case should be supported out of the box in every scenario.

**Comment by David-Desmaisons** [comment]
So if I understand, you are calling Neutronium application from another application(same process). But at the same time, the two processes are located in different folders correct?

Could you try the following fix in
[ChromiumFXSession.cs](Neutronium/WebBrowserEngine/ChromiumFX/HTMEngine.ChromiumFX/Session/ChromiumFXSession.cs):

line 38:
```C#
var codeBase = this.GetType().Assembly.CodeBase;
var uri = new UriBuilder(codeBase);
string directory= System.IO.Path.GetDirectoryName( Uri.UnescapeDataString(uri.Path));
settings.LocalesDirPath= System.IO.Path.Combine (directory, @"cef\Resources\locales");
settings.ResourcesDirPath= System.IO.Path.Combine (directory, @"cef\Resources");
settings.BrowserSubprocessPath= System.IO.Path.Combine(directory, "ChromiumFXRenderProcess.exe");
```


?

**Comment by jmecosta** [comment]
weird, in principle that would solve it. but it does not :(

this is the way i call the application:

![image](https://cloud.githubusercontent.com/assets/1041352/20167744/280101e8-a726-11e6-83c5-06de05667abe.png)

then i still get this exception:
```
Description: The process was terminated due to an unhandled exception.
Exception Info: Chromium.CfxException
   at Chromium.CfxApi.FindLibraries(System.String ByRef, System.String ByRef)
   at Chromium.CfxApi.Load()
   at Chromium.CfxApi.Probe()
   at Chromium.CfxRuntime.ExecuteProcess(Chromium.CfxApp)
   at Chromium.CfxRuntime.ExecuteProcess()
   at Chromium.WebBrowser.BrowserProcess.Initialize()
   at Chromium.WebBrowser.ChromiumWebBrowser.Initialize()
   at Neutronium.WebBrowserEngine.ChromiumFx.Session.ChromiumFxSession..ctor(System.Action`1<Chromium.CfxSettings>, System.Action`1<Chromium.Event.CfxOnBeforeCommandLineProcessingEventArgs>)
   at Neutronium.WebBrowserEngine.ChromiumFx.Session.ChromiumFxSession.GetSession(System.Action`1<Chromium.CfxSettings>, System.Action`1<Chromium.Event.CfxOnBeforeCommandLineProcessingEventArgs>)
   at Neutronium.WebBrowserEngine.ChromiumFx.ChromiumFXWPFWebWindowFactory..ctor(System.Action`1<Chromium.CfxSettings>, System.Action`1<Chromium.Event.CfxOnBeforeCommandLineProcessingEventArgs>)
   at Neutronium.WebBrowserEngine.ChromiumFx.ChromiumFxWebBrowserApp.GetWindowFactory()
   at Neutronium.WPF.HTMLApp.OnStartup(System.Windows.StartupEventArgs)
   at System.Windows.Application.<.ctor>b__1_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at BuildAllApp.App.Main()
```

by the way i notice that some libs are deployed also. this cef_sandbox.lib is 200MB and made my app explode. Ive remove those libs from the package and everything seems to work. are those really needed?

**Comment by David-Desmaisons** [comment]
1) Regarding  cef_sandbox.lib, you are correct, I will remove this file from next version of chromium.

2) Regarding the inicial issue, did taking-out this file actually solve it?

**Comment by jmecosta** [comment]
2) nop, ive been already packaging my app without the libs. so not sure whats going on there, perhaps i applied the patch incorrectly or something

**Comment by David-Desmaisons** [comment]
Could you please check the path of the cef folder in your deploy scenario and compare it to:
´´´´
var codeBase = this.GetType().Assembly.CodeBase;
var uri = new UriBuilder(codeBase);
string directory= System.IO.Path.GetDirectoryName( Uri.UnescapeDataString(uri.Path));
´´´´

**Comment by jmecosta** [comment]
```
settings.LocalesDirPath= System.IO.Path.Combine (directory, @"cef\Resources\locales");
settings.ResourcesDirPath= System.IO.Path.Combine (directory, @"cef\Resources");
```

this looks exactly what i have:

![image](https://cloud.githubusercontent.com/assets/1041352/20183137/06bd7a9c-a76d-11e6-9fe9-5f35aa63aca9.png)

cef:
![image](https://cloud.githubusercontent.com/assets/1041352/20183151/0e790364-a76d-11e6-999a-a1ed1a42b15e.png)

i can try wiht the samples to see if it works

**Comment by jmecosta** [comment]
no the samples dont work either:

![image](https://cloud.githubusercontent.com/assets/1041352/20183554/67171f00-a76e-11e6-915e-dbb3b8bdf857.png)

ChromiumFXWPFWebWindowFactory.cs also contains loading path information. ive change that one also, but did not seem to work either

**Comment by David-Desmaisons** [comment]
Do you hav ChromiumRederFxProcess .exe in the same folder?

**Comment by David-Desmaisons** [comment]
@jmecosta You shoul also alter line 19:
```
            CfxRuntime.LibCefDirPath = @"cef\Release";
```
using same logic as other lines...

**Comment by jmecosta** [comment]
ok, after changing all those it works. do you want a pul request?

**Comment by David-Desmaisons** [comment]
I should perform some code refactoring, so you don't need to open a PR. I should commit the change today at nigth.

Expect a new version by the end of the week-end.

**Comment by jmecosta** [comment]
please close when your ready, thanks

**Comment by David-Desmaisons** [comment]
The new package vesrion (Neutronium.ChromiumFx 0.3.0) contains this fix.

**Comment by jmecosta** [comment]
@David-Desmaisons everything is working fine now, and the size of the package did not change. thanks
